[package]
name = "branches"
version = "0.1.0"
authors = ["Julian BÃ¼cher <Julian.Buecher@STPAG2014.onmicrosoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
